---
engines:
  ansiblereview:
    enabled: true
    config:
      git_rules_repo: http://10.10.10.18/gitlab/Rob/ansible-standards-lint/repository/master/archive.zip
      work_dir: /var/tmp/ansiblereview-rules
      standards_dir: standards
      lint_dir: lint-rules
